import Head from 'next/head';
import LayoutAbout from '../src/components/layout/layout-about';

export default function About() {
  return (
    <LayoutAbout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </LayoutAbout>
  );
}
