import Head from 'next/head';
import LayoutPortfolio from '../src/components/layout/layout-portfolio';

export default function Portfolio() {
  return (
    <LayoutPortfolio>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </LayoutPortfolio>
  );
}
