import Head from 'next/head';
import LayoutServices from '../src/components/layout/layout-services';

export default function Services() {
  return (
    <LayoutServices>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </LayoutServices>
  );
}
